"""Adicionando colunas faltantes

Revision ID: 29dc89214c18
Revises: 640ad60c7294
Create Date: 2026-04-12 12:45:26.480675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dc89214c18'
down_revision = '640ad60c7294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
