"""Adicionando colunas faltantes

Revision ID: 33b7b59a565a
Revises: 8a1b2c3d4e5f
Create Date: 2026-04-12 19:17:18.229941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b7b59a565a'
down_revision = '8a1b2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_funcional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('nivel_hierarquico', sa.Integer(), nullable=False),
    sa.Column('pode_atribuir_balanco', sa.Boolean(), nullable=True),
    sa.Column('pode_executar_balanco', sa.Boolean(), nullable=True),
    sa.Column('pode_validar_balanco', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tarefa_balanco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('contexto', sa.String(length=80), nullable=True),
    sa.Column('tipo_operacao', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=True),
    sa.Column('quantidade_esperada', sa.Float(), nullable=False),
    sa.Column('quantidade_realizada', sa.Float(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('corredor_destino', sa.String(length=50), nullable=True),
    sa.Column('prateleira_destino', sa.String(length=50), nullable=True),
    sa.Column('observacoes_execucao', sa.Text(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_funcional_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gestor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'perfil_funcional', ['perfil_funcional_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['gestor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gestor_id')
        batch_op.drop_column('perfil_funcional_id')

    op.drop_table('tarefa_balanco')
    op.drop_table('perfil_funcional')
    # ### end Alembic commands ###
