"""Adicionando colunas faltantes

Revision ID: 3ca58a433a0a
Revises: c3d4e5f6a7b8
Create Date: 2026-05-27 20:21:40.387292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ca58a433a0a'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('products')
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('api_token'))
        batch_op.drop_index(batch_op.f('celular'))
        batch_op.drop_index(batch_op.f('cnpj'))
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('sellers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cnpj', mysql.VARCHAR(length=18), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('celular', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Inativo'"), nullable=False),
    sa.Column('activation_code', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('api_token', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('celular'), ['celular'], unique=True)
        batch_op.create_index(batch_op.f('api_token'), ['api_token'], unique=True)

    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('preco', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('quantidade', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Ativo'"), nullable=False),
    sa.Column('imagem', mysql.MEDIUMTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_products_seller')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sales',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade_vendida', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_produto_momento_venda', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_product')),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_sales_seller')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
