"""Adicionando colunas faltantes

Revision ID: 48271f5dfe1f
Revises: 33b7b59a565a
Create Date: 2026-05-25 21:36:12.573256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48271f5dfe1f'
down_revision = '33b7b59a565a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_funcional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('nivel_hierarquico', sa.Integer(), nullable=False),
    sa.Column('pode_atribuir_balanco', sa.Boolean(), nullable=True),
    sa.Column('pode_executar_balanco', sa.Boolean(), nullable=True),
    sa.Column('pode_validar_balanco', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('classe', sa.String(length=50), nullable=True),
    sa.Column('first_login_completed', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('ramal', sa.String(length=20), nullable=True),
    sa.Column('numero_corporativo', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=50), nullable=True),
    sa.Column('perfil_funcional_id', sa.Integer(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.ForeignKeyConstraint(['gestor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['obra.id'], ),
    sa.ForeignKeyConstraint(['perfil_funcional_id'], ['perfil_funcional.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('especificacao_id', sa.Integer(), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('valorPeso', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['especificacao_id'], ['especificacao.id'], ),
    sa.ForeignKeyConstraint(['familia_id'], ['familia.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('patrimonio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_patrimonio', sa.String(length=50), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_compra', sa.Date(), nullable=True),
    sa.Column('fim_garantia', sa.Date(), nullable=True),
    sa.Column('valor_compra', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_patrimonio'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('corredor', sa.String(length=50), nullable=True),
    sa.Column('prateleira', sa.String(length=50), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('preco_promocional', sa.Float(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefa_balanco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('contexto', sa.String(length=80), nullable=True),
    sa.Column('tipo_operacao', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=True),
    sa.Column('quantidade_esperada', sa.Float(), nullable=False),
    sa.Column('quantidade_realizada', sa.Float(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=False),
    sa.Column('corredor_destino', sa.String(length=50), nullable=True),
    sa.Column('prateleira_destino', sa.String(length=50), nullable=True),
    sa.Column('observacoes_execucao', sa.Text(), nullable=True),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('products')
    op.drop_table('sales')
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('api_token'))
        batch_op.drop_index(batch_op.f('celular'))
        batch_op.drop_index(batch_op.f('cnpj'))
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('sellers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('cnpj', mysql.VARCHAR(length=18), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('celular', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Inativo'"), nullable=False),
    sa.Column('activation_code', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('api_token', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('celular'), ['celular'], unique=True)
        batch_op.create_index(batch_op.f('api_token'), ['api_token'], unique=True)

    op.create_table('sales',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantidade_vendida', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preco_produto_momento_venda', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_product')),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_sales_seller')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('preco', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('quantidade', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Ativo'"), nullable=False),
    sa.Column('imagem', mysql.MEDIUMTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_products_seller')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tarefa_balanco')
    op.drop_table('produto')
    op.drop_table('patrimonio')
    op.drop_table('sku')
    op.drop_table('user')
    op.drop_table('tipo')
    op.drop_table('perfil_funcional')
    op.drop_table('obra')
    op.drop_table('marca')
    op.drop_table('familia')
    op.drop_table('especificacao')
    op.drop_table('departamento')
    # ### end Alembic commands ###
