"""Add missing columns

Revision ID: 640ad60c7294
Revises: 
Create Date: 2026-03-07 16:58:42.313782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640ad60c7294'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('familia_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'familia', ['familia_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('familia_id')

    # ### end Alembic commands ###
